### ISSUE TITLE
Port extension to Firefox

### ISSUE THREAD

**Issue by lheinke** [Haaxor1689/humble-steam-sync#1]
Hey @Haaxor1689,
I would be interested in a port of the extension to the Firefox Browser. Using the [Extension Compatibility Test for Firefox](https://www.extensiontest.com/) it seems like the one major problem for a cross-browser compatible extension would be the manifest version. Version 3 is not supported by Firefox at this time. One could therefore either downgrade the manifest to version 2 or create a separate branch/fork for a Firefox extension. Which of these options would you prefer? I would be willing to help but have no prior experience in developing browser extensions.

**Comment by Haaxor1689** [comment]
Hi, thanks for reaching out. I looked at some guides on Firefox extension development and it is indeed not that hard to make it cross-browser compatible. So easy in fact I've made a Firefox version just now.

It will be available at this link after the review:

https://addons.mozilla.org/en-US/firefox/addon/steam-tags-for-humble-bundle/
