### ISSUE TITLE
"an error occurred"

### ISSUE THREAD

**Issue by Termuellinator** [Haaxor1689/humble-steam-sync#10]
Hi there!

really love your work here, but since about a week or so i just get
```
Steam tags extension

An error occurred
```
When loading a humblebundle page.
It might coincide with me creating a new Firefox-Profile, but i also get that error now on the old profile where it definitely worked in the past.

I've found no way to further inspect the error - maybe someone has an idea?

**Comment by WarWraith** [comment]
Having the same problem on Chrome. The extension will show me as logged in, but the Humble Bundle page throws up an error with "Please login to Steam store or enter your SteamId in extension settings".

If I log out, and try to log back in, I just get "An error occurred" on the Extension.

Inspect Popup shows "DevTools failed to load source map: Could not load content for chrome-extension://fcinjfniedmmfaalakcallcbjepfiabi/browser-polyfill.min.js.map: System error: net::ERR_FILE_NOT_FOUND"

Even with that error, when I try to log in, the Inspector shows:
GET https://humble-steam-sync.herokuapp.com/76561197965691494/profile 503 (Service Unavailable)
popup.js:92

As Heroku recently removed their free tier, I suspect the extension has been a victim of its own success.

**Comment by Haaxor1689** [comment]
Oh damn you heroku. I'll need to find a replacement. Thanks for providing detailed info :)

**Comment by Termuellinator** [comment]
That´s an easy explanation at least ^^
Thanks for the analysis @WarWraith !

**Comment by ardittristan** [comment]
You could probably use cloudflare workers, as long as you don't expect more than 100k requests/day it's free (and I think if you hit the limit it just stops working for the day)
![image](https://user-images.githubusercontent.com/42787508/222815669-0c3ec66b-0c99-40b9-ba81-8ee0cb293708.png)

**Comment by ardittristan** [comment]
Here's https://github.com/Haaxor1689/humble-steam-sync/blob/master/web/index.ts converted to a cloudflare worker script: https://gist.github.com/ardittristan/6b23c9eb56b031795caadc80a72d127b

**Comment by Haaxor1689** [comment]
Finally got around to rewriting this extension and getting it working again. A new version was submitted to Chrome, so in a few days it should be up. New firefox version should already be up :)
