### ISSUE TITLE
Titles with : doesn't get recognized

### ISSUE THREAD

**Issue by PietroPizzi69** [Haaxor1689/humble-steam-sync#11]
In the ongoing "Unparalleled Puzzlers" Bundle I have "Monument Valley: Panoramic Edition" (and 2) in my lib and "DARQ: Complete Edition" in my wishlist but non of them gets a Tag.

**Comment by Haaxor1689** [comment]
I'll need to manually handle some games since humble bundle sometimes has a different name for them than Steam does and there is no id visible on the page I could reference back to steam db. I'll look into it.

**Comment by Haaxor1689** [comment]
I've added a "Report missing tag" feature to the 2.1 release that is live on Firefox and should be live soon on Chrome after it goes through review. Going forward, any tag you will notice is missing, can be reported using this.
