### ISSUE TITLE
Request: Link Directly To Apps (Where Possible)

### ISSUE THREAD

**Issue by richard-jr-lewis** [Haaxor1689/humble-steam-sync#12]
Hey, loving the extension, it's proving really useful. Feature request for what I would hope is straightforward to implement. I believe the data is available from the APIs:

> Given a user's data includes AppIds
> When a game is identified as `IN LIBRARY` etc...
> Then the URL directly links to the AppId

e.g. if Hollow Knight (AppId 367520) is in a user's library, instead of the `IN LIBRARY` tag linking to `https://store.steampowered.com/search/?term=Hollow%20Knight`, it will link to `https://store.steampowered.com/app/367520`. If a match is not possible, it will behave as currently.

**Comment by Haaxor1689** [comment]
That's a good suggestion :) I've added it and it should be available soon after the update is approved by Chrome and Firefox

**Comment by richard-jr-lewis** [comment]
Wow, that was fast! Nice work!
