### ISSUE TITLE
Login doesn't work on Firefox after 2.5 update

### ISSUE THREAD

**Issue by meve90** [Haaxor1689/humble-steam-sync#13]
error say "Could not establish connection. Receiving end does not exist."

And if I try to put my id and click the log in icon nothing happen

I used this extension for months with no issue before this update

**Comment by Haaxor1689** [comment]
HI, thanks for the report, did you update to the latest version?

**Comment by meve90** [comment]
It's on 2.5 yes, I downloaded from https://addons.mozilla.org/en-US/firefox/addon/steam-tags-for-humble-bundle/ I even tried to uninstall and reinstall

On version 2.4 it was actually working fine

**Comment by Haaxor1689** [comment]
Will be fixed in v2.6. I've submitted it for review so should be out within a day.

**Comment by meve90** [comment]
it now work thx

it does say this tough "Please, grant all required permissions to this extension, for it to function properly" even with all flagged permission on, it's still working so is not important

**Comment by Haaxor1689** [comment]
When you click the button next to the message, does it open a dialog asking to add some permissions? Also do you have all chekboxes checked on this screen?
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/25706343/eeecd0da-43e3-4ce7-a2c9-df3c7b0e58e1)

**Comment by meve90** [comment]
It doesn't open the box when I click but I check the permission manually and they are all on
![permission](https://github.com/Haaxor1689/humble-steam-sync/assets/14894316/af6f506f-8027-46e1-9cbc-a386e8a0dbc8)
![permission1](https://github.com/Haaxor1689/humble-steam-sync/assets/14894316/4b8f9967-9d53-4e33-9cbe-931aebd6e014)
