### ISSUE TITLE
Could not establish connection Problem

### ISSUE THREAD

**Issue by Vasharal** [Haaxor1689/humble-steam-sync#14]
Hello,

I've been using your add-on on Firefox in the past couple of months and I've been loving it, but recently I've noticed that I can't access it anymore so I can use it. This happened when I switched from Windows 10 to Windows 11, but I doubt that's really the issue.

The [error](https://i.imgur.com/Ui9e2dU.png) I'm getting is this: "Could not establish connection. Receiving end does not exist."

I've also tried using https://steamcommunity.com/id/Vasharal/ but with no avail.

What am I doing wrong and how could I fix this? Thanks!

**Comment by Haaxor1689** [comment]
Will be fixed in v2.6. I've submitted it for review so should be out within a day.
