### ISSUE TITLE
Chrome - Grant Permissions Doesn't Work

### ISSUE THREAD

**Issue by richard-jr-lewis** [Haaxor1689/humble-steam-sync#15]
Extension was working fine at v2.4 and I think v2.5. With v2.6, it's "forgotten" me and says I require permissions to be granted.
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/20093536/3225d45f-13d8-49d5-a728-d82eee803290)

Pressing the "unlock" button doesn't do anything. Going to the Extensions page in Chrome and viewing the extension settings doesn't show anything extra to grant permissions to.
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/20093536/e72609d4-2223-4621-90cb-811647c15f20)

Not quite sure what's going on.

**Comment by Haaxor1689** [comment]
That's just a visual issue since you have extra permissions from older version there. I'll push a fix for it soon :)

**Comment by richard-jr-lewis** [comment]
Sadly I think it's more than that. My "logged in" user details are missing.

If I fill in my name again and click "log in", nothing seems to happen. If I then refresh the page, my name disappears. The "retry" button doesn't appear to do anything. Clicking the link to go to steam shows me as logged in there.

I've claimed all the keys from this Choice, but you can see I'm not "logged in".
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/20093536/a9fb80ec-ede9-4052-b852-893c0ce75782)

**Comment by Haaxor1689** [comment]
oh I see, so clicking either of the login option show absolutely nothing?

**Comment by Haaxor1689** [comment]
oh I know what might be the problem, did you try removing it from chrome and added it back? it might be crashing because of old cached data

**Comment by Haaxor1689** [comment]
I've submitted new version 2.7 that should be available within next day, let me know if it fixes the issue for you :)

**Comment by richard-jr-lewis** [comment]
Looks good!
