### ISSUE TITLE
Can't "login" with SteamID nor CustomURL

### ISSUE THREAD

**Issue by LoVega1337** [Haaxor1689/humble-steam-sync#16]
Entering the SteamID or CustomURL just loads a second and then goes back like I entered nothing. ServiceWorker shows:
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/47011400/e5274b60-947f-48dd-9564-ddaf71b06604)

**Comment by Haaxor1689** [comment]
Thanks for the report. Try resetting your local data.

**Comment by LoVega1337** [comment]
Cheers, it worked. Didn't come to my mind to reset the data for the extension.
Should I keep the issue open for a potential bug fix that if this issue happens, the local data e.g. automatically deletes itself?

**Comment by Haaxor1689** [comment]
Yeah keep it open so I have a reminder to go check how it could have gotten to this incorrect state.
