### ISSUE TITLE
Extension popup is too narrow

### ISSUE THREAD

**Issue by Spurlos** [Haaxor1689/humble-steam-sync#17]
It looks like after recent updates of CSS the body of popup in the Chrome extensions tray is broken. Although it has flex set and max-width, it seems nothing is pushing the content up to its desired boundaries.

Tested on Chrome 116.0.5845.62

![Screenshot from 2023-08-10 15-54-58](https://github.com/Haaxor1689/humble-steam-sync/assets/667533/fd145ca3-02e5-49fc-ad07-6c2a041d42c1)

**Comment by Haaxor1689** [comment]
Thanks for the report, I finally go the 116 version update for Chrome myself and I've posted new version 2.8 of the addon with a fix. Should be up in few days.
