### ISSUE TITLE
Store page width issue

### ISSUE THREAD

**Issue by Spurlos** [Haaxor1689/humble-steam-sync#21]
I am experiencing an issue with the store layout being shrunk while using this extension.

Issue preview:
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/667533/ce62703f-4f36-43e3-82cc-77a633662b75)

I have pinned down the issue to this particular style sheet file:
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/667533/49d068bb-a91c-4162-903d-b1c62f5dffd5)
![image](https://github.com/Haaxor1689/humble-steam-sync/assets/667533/527ec793-1c5b-45f8-aa90-ddffd9c32d73)

I haven't found explicit set of width for root HTML tag in your code, so its likely that postcss compiler is adding this.

Setting html tag width CSS property to auto return things to normal as an override. But it seems that we don't need to override the tag in first place.

Please tame your styles and happy debugging!

**Comment by Haaxor1689** [comment]
Pushed new v2.9 build, should be fixed once it's released
