### ISSUE TITLE
Just "Loading..."

### ISSUE THREAD

**Issue by LoVega1337** [Haaxor1689/humble-steam-sync#3]
I noticed that the extenstion stopped working more or less. The little windows just says "Loading..." but never finishes. I can't tell if they would still get marked though (in another bundle) because I don't own these games below nor are they wishlisted, I manually checked.

EDIT: Just checked with owned games in the store, it is indeed not working at all.

![image](https://user-images.githubusercontent.com/47011400/150845330-156ab516-e1c0-4fc6-b667-d1e07ffaaf72.png)

**Comment by Haaxor1689** [comment]
@LoVega1337 are you either logged into `https://store.steampowered.com/` or through the extension options?

**Comment by LoVega1337** [comment]
Just through the Extension Options and it also fetched my games and wishlist data no problem.

**Comment by Haaxor1689** [comment]
And are you on chrome or mozilla?

**Comment by LoVega1337** [comment]
Ah forgot to mention, Chrome 97.0.4692.99

**Comment by Haaxor1689** [comment]
What steam url/id are you using? If you go to the extension options do you see numbers of items saved?

**Comment by LoVega1337** [comment]
I used my custom URL and like I said, it did fetch my data normally.
![image](https://user-images.githubusercontent.com/47011400/150850829-5ce44723-e004-4c99-9db3-ca1147e9ad61.png)

**Comment by Haaxor1689** [comment]
Have you tried reinstalling the extension? In the last update I removed some permissions and it may not have migrated properly.

**Comment by LoVega1337** [comment]
Just tried, still not working.
Try to use mine URL, maybe something is bugged with my specific list.
![image](https://user-images.githubusercontent.com/47011400/150852423-93d4a30b-3ac9-4c5c-82ce-f18fa5b5ea36.png)

**Comment by Haaxor1689** [comment]
Hmm it works for me with you profile, do you maybe have some other extension that could affect it?

Could you go into `chrome://extensions/`, enable developer mode, then in extension details enable `Collect errors`? Then after reloading the humble page there should probably be errors where the cursor is

![image](https://user-images.githubusercontent.com/25706343/150855000-2cab65be-e86c-4b68-a5da-6a8e5cd757ab.png)

or when you click `background page` there may be error here

![image](https://user-images.githubusercontent.com/25706343/150855211-66b4cf29-2710-433d-93e3-75aa24c80121.png)

**Comment by LoVega1337** [comment]
Getting greeted with this error:
![image](https://user-images.githubusercontent.com/47011400/150856060-489a804c-2411-49ff-a2f6-2d704d65acf5.png)

**Comment by Haaxor1689** [comment]
Ah great, I'll look into that, thanks for cooperation

**Comment by Haaxor1689** [comment]
I've submitted new version **v1.4** with a fix for this issue for review for both Chrome and Firefox extension stores

**Comment by LoVega1337** [comment]
Got the update and it works again now, thanks!
