### ISSUE TITLE
The extension doesn't work on Choice pages.

### ISSUE THREAD

**Issue by AdamEternal** [Haaxor1689/humble-steam-sync#4]
The extension works on www.humblebundle.com/home/library (although the extension is missing some games in my Steam library), but doesn't even show a loading sign on Humble Choice pages like www.humblebundle.com/membership/june-2021. I _know_ that I have Civilization 6 on Steam, for example, but the extension doesn't show that on the Humble Choice page.

**Comment by Haaxor1689** [comment]
Will be fixed in next release.
