### ISSUE TITLE
Mismatched data?

### ISSUE THREAD

**Issue by AdamEternal** [Haaxor1689/humble-steam-sync#5]
Comparing what the extension says in its saved data and what my Steam library says doesn't match up. Steam says that I've got 717 games and 31 wishlisted, whereas the extension's saved data says that I have 1,286 library items and 30 wishlisted. Checking my wishlist, 2 of my wishlisted games are without price, so I'm not sure why the extension is missing _one_ item. As for the "library items," is that supposed to be _just_ my games, or does that include my inventory, such as cards?

**Comment by Haaxor1689** [comment]
This is caused by the way steam handles items and bundles. Some store pages represent multiple items, some represent bundles that contain multiple items. I don't think there is an easy way of getting the number showing in the extension to the same value as shown on the steam store page sadly.
